# Site settings
title: SkuldNet
email:
description: > # this means to ignore newlines until "baseurl:"
  Website of the SkuldNet consciousness consortium.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://locahost:4000" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
